### ISSUE TITLE
hey ochii

### ISSUE THREAD

**Issue by loonbg** [Ochii/cso2-launcher#10]
hello and thanks for your work on cso2 👍 

i saw that your launcher bypass login and can be played without him
and want to ask you if you have time .. can you take look at this game
https://gameborder.net/file/kos-secret-operations
https://www.lonebullet.com/file/clients/kos-secret-operations-v14481017-us-client/1205
 its also based on Source Engine .. game died before 1-2 years ;( if there is anyway to be played offline or online with friends will be really awesome

**Comment by Ochii** [comment]
Sorry, I'm focused on cso2 right now
