### ISSUE TITLE
Capstone fails to build

### ISSUE THREAD

**Issue by herowudi** [Ochii/cso2-launcher#13]
8>LINK : fatal error LNK1104: Cannot open file “capstone.lib”

**Comment by herowudi** [comment]
New Issues 
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "H:/cso2-launcher-master/nnnnnnnnn/cso2-launcher/libs/PolyHook_2_0/capstone/build32/CMakeFiles/CMakeOutput.log"
.
See also "H:/cso2-launcher-master/nnnnnnnnn/cso2-launcher/libs/PolyHook_2_0/capstone/build32/CMakeFiles/CMakeError.log".

-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

**Comment by Ochii** [comment]
What version of Powershell do you have? Send the output from ```echo $PSVersionTable.PSVersion```.

Do you have Microsoft Visual Studio installed?

**Comment by herowudi** [comment]
> What version of Powershell do you have? Send the output from `echo $PSVersionTable.PSVersion`.
> 
> Do you have Microsoft Visual Studio installed?

Sorry my title is wrong,I managed to run it .
This problem is happened when I tried to make Launch.exe in VS2017

8>filesystem_init.cpp
8>consolethread.cpp
8>正在生成代码...
8>LINK : fatal error LNK1104: 无法打开文件“capstone.lib”
8>已完成生成项目“launcher.vcxproj”的操作 - 失败(Fail)。
========== 生成: 成功 0 个，失败(Fail) 1 个，最新 0 个，跳过(Skip) 7 个 ==========

**Comment by herowudi** [comment]
These are what happened in the powershell
  
  目录: D:\fuwuduan\4n\cso2-launcher\libs\PolyHook_2_0\capstone


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----        2018/11/18      1:44            build32
d----        2018/11/18      1:44            build64
-- The C compiler identification is MSVC 19.16.27023.1
-- The CXX compiler identification is MSVC 19.16.27023.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023
/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023
/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.270
23/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.270
23/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:18 (cmake_policy):
  The OLD behavior for policy CMP0048 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


Enabling CAPSTONE_ARM_SUPPORT
Enabling CAPSTONE_ARM64_SUPPORT
Enabling CAPSTONE_M68K_SUPPORT
Enabling CAPSTONE_MIPS_SUPPORT
Enabling CAPSTONE_PPC_SUPPORT
Enabling CAPSTONE_SPARC_SUPPORT
Enabling CAPSTONE_SYSZ_SUPPORT
Enabling CAPSTONE_XCORE_SUPPORT
Enabling CAPSTONE_X86_SUPPORT
Enabling CAPSTONE_TMS320C64X_SUPPORT
Enabling CAPSTONE_M680X_SUPPORT
Enabling CAPSTONE_EVM_SUPPORT
-- Configuring done
-- Generating done
-- Build files have been written to: D:/fuwuduan/4n/cso2-launcher/libs/PolyHook_2_0/capstone/build32
-- The C compiler identification is MSVC 19.16.27023.1
-- The CXX compiler identification is MSVC 19.16.27023.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023
/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023
/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.270
23/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.270
23/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/fuwuduan/4n/cso2-launcher/libs/PolyHook_2_0

D:\fuwuduan\4n\cso2-launcher\libs\source-sdk-cso2>devtools\bin\vpc.exe /define:VS2017 +launcher
VPC - Valve Project Creator For Visual Studio, Xbox 360, PlayStation 3, Xcode and Make (Build: Aug 27 2014 12:55:48)
(C) Copyright 1996-2010, Valve Corporation, All rights reserved.

Source Path: D:\fuwuduan\4n\cso2-launcher\libs\source-sdk-cso2
Target Platform: win32
Generating for Visual Studio 2013.

Parsing: appframework.vpc
Saving... Project: 'appframework' File: 'appframework.vcxproj'

Parsing: mathlib.vpc
Saving... Project: 'mathlib' File: 'mathlib.vcxproj'

Parsing: tier1.vpc
Saving... Project: 'tier1' File: 'tier1.vcxproj'

Parsing: tier2.vpc
Saving... Project: 'tier2' File: 'tier2.vcxproj'

Parsing: tier3.vpc
Saving... Project: 'tier3' File: 'tier3.vcxproj'

**Comment by herowudi** [comment]
when I built PolyHook2,the problem is:
1>LINK : fatal error LNK1104: Cannot open “capstone\build32\Debug\capstone.lib”

**Comment by herowudi** [comment]
Can u send me "capstone.lib"?

**Comment by herowudi** [comment]
> Could you try building the latest commit?

Yes,it is the latest,after I tried my best to fix the missing problem,I finally got crazy too many errors...
![image](https://user-images.githubusercontent.com/30003227/48664633-859a8080-eadc-11e8-9840-28f7977a4871.png)

**Comment by herowudi** [comment]
> Could you try building the latest commit?

the errors are divided to 3 kinds
One is redefine
Two is value not match
Three is library is conflict
Can u help me。。。

**Comment by Ochii** [comment]
Try redownloading the project

**Comment by herowudi** [comment]
> Could you try building the latest commit?

I tried ur latest 
whats wrong with these head file?



 ,D:\fuwuduan\cso2-launcher-0.1.5-1\cso2-launcher-0.1.5-1\cso2-launcher\libs\PolyHook_2_0\capstone\cs.c(11): fatal error
C1083: 无法打开包括文件: “stddef.h”: No such file or directory [D:\fuwuduan\cso2-launcher-0.1.5-1\cso2-launcher-0.1.5-1\
cso2-la
uncher\libs\PolyHook_2_0\capstone\build64\capstone-static.vcxproj]
  MCInst.c
D:\fuwuduan\cso2-launcher-0.1.5-1\cso2-launcher-0.1.5-1\cso2-launcher\libs\PolyHook_2_0\capstone\MCInst.c(8): fatal err
or C1083: 无法打开包括文件: “stdio.h”: No such file or directory [D:\fuwuduan\cso2-launcher-0.1.5-1\cso2-launcher-0.1.5-
1\cso2-
launcher\libs\PolyHook_2_0\capstone\build64\capstone-static.vcxproj]
  MCInstrDesc.c
D:\fuwuduan\cso2-launcher-0.1.5-1\cso2-launcher-0.1.5-1\cso2-launcher\libs\PolyHook_2_0\capstone\include\capstone/platf
orm.h(119): fatal error C1083: 无法打开包括文件: “inttypes.h”: No such file or directory [D:\fuwuduan\cso2-launcher-0.1.
5-1\cso
2-launcher-0.1.5-1\cso2-launcher\libs\PolyHook_2_0\capstone\build64\capstone-static.vcxproj]
  MCRegisterInfo.c
D:\fuwuduan\cso2-launcher-0.1.5-1\cso2-launcher-0.1.5-1\cso2-launcher\libs\PolyHook_2_0\capstone\include\capstone/platf
orm.h(119): fatal error C1083: 无法打开包括文件: “inttypes.h”: No such file or directory [D:\fuwuduan\cso2-launcher-0.1.
5-1\cso
2-launcher-0.1.5-1\cso2-launcher\libs\PolyHook_2_0\capstone\build64\capstone-static.vcxproj]
  SStream.c
D:\fuwuduan\cso2-launcher-0.1.5-1\cso2-launcher-0.1.5-1\cso2-launcher\libs\PolyHook_2_0\capstone\SStream.c(10): fatal e
rror C1083: 无法打开包括文件: “stdio.h”: No such file or directory [D:\fuwuduan\cso2-launcher-0.1.5-1\cso2-launcher-0.1.
5-1\cso
2-launcher\libs\PolyHook_2_0\capstone\build64\capstone-static.vcxproj]
  utils.c
D:\fuwuduan\cso2-launcher-0.1.5-1\cso2-launcher-0.1.5-1\cso2-launcher\libs\PolyHook_2_0\capstone\utils.c(8): fatal erro
r C1083: 无法打开包括文件: “stdlib.h”: No such file or directory [D:\fuwuduan\cso2-launcher-0.1.5-1\cso2-launcher-0.1.5-
1\cso2-
launcher\libs\PolyHook_2_0\capstone\build64\capstone-static.vcxproj]
  X86Disassembler.c
D:\fuwuduan\cso2-launcher-0.1.5-1\cso2-launcher-0.1.5-1\cso2-launcher\libs\PolyHook_2_0\capstone\include\capstone/platf
orm.h(119): fatal error C1083: 无法打开包括文件: “inttypes.h”: No such file or directory [D:\fuwuduan\cso2-launcher-0.1.
5-1\cso
2-launcher-0.1.5-1\cso2-launcher\libs\PolyHook_2_0\capstone\build64\capstone-static.vcxproj]

**Comment by herowudi** [comment]
![image](https://user-images.githubusercontent.com/30003227/48664908-f2177e80-eae0-11e8-844e-04904a407a2e.png)

**Comment by herowudi** [comment]
> 改Windows SDK版本 改成你装了的版本
> 
> Change the Windows SDK version to the version that you have installed

有QQ吗 windwossdk我装了3个版本环境变量都填了目录

**Comment by Ochii** [comment]
Which project files are you referring to @GEEKiDoS? Did you have this issue too?

```launcher.vcxproj``` and the Source SDK's use Windows SDK 8.1.

PolyHook's and capstone's project files are generated through CMake, which I believe it sets the SDK version to the latest it can find.

Capstone source code has Visual Studio project files, I could switch to them. The only library that doesn't have is PolyHook.

**Comment by herowudi** [comment]
> Which project files are you referring to @GEEKiDoS? Did you have this issue too?
> 
> `launcher.vcxproj` and the Source SDK's use Windows SDK 8.1.
> 
> PolyHook's and capstone's project files are generated through CMake, which I believe it sets the SDK version to the latest it can find.
> 
> Capstone source code has Visual Studio project files, I could switch to them. The only library that doesn't have is PolyHook.

the question above was solved ,then NEW question is coming.
Yup,now when I changed launcher.vcxproj`s SDK version to Windows SDK10 10.0.17763,
it works,BUT I cant make PolyHook_2.dll ,it doesnt exist,so built errror

**Comment by Ochii** [comment]
> the question above was solved ,then NEW question is coming.
> Yup,now when I changed launcher.vcxproj`s SDK version to Windows SDK10 10.0.17763,
> it works,BUT I cant make PolyHook_2.dll ,it doesnt exist,so built errror

Which errors do you get when building PolyHook?

**Comment by GEEKiDoS** [comment]
> Which project files are you referring to @GEEKiDoS? Did you have this issue too?
> 
> `launcher.vcxproj` and the Source SDK use Windows SDK 8.1.
> 
> PolyHook's and capstone's project files are generated through CMake, which I believe it sets the SDK version to the latest it can find.
> 
> Capstone source code has Visual Studio project files. If necessary I could use them instead of generating the files. The only library that doesn't come with Visual Studio project files is PolyHook.

I didn't install the Windows 8.1 SDK,So I just change the windows SDK Version to Windows 10. It's ok and runs good after complied

**Comment by Ochii** [comment]
> 
> I didn't install the Windows 8.1 SDK,So I just change the windows SDK Version to Windows 10. It's ok and runs good after complied

Do you think we should use CMake or some other build system? I would like for everyone to be able to build this easily

**Comment by herowudi** [comment]
> > I didn't install the Windows 8.1 SDK,So I just change the windows SDK Version to Windows 10. It's ok and runs good after complied
> 
> Do you think we should use CMake or some other build system? I would like for everyone to be able to build this easily

I dont know if the whole scripts will work fine，you can try to write every step to the script then write how to configurate environment step by step

**Comment by herowudi** [comment]
> > I didn't install the Windows 8.1 SDK,So I just change the windows SDK Version to Windows 10. It's ok and runs good after complied
> 
> Do you think we should use CMake or some other build system? I would like for everyone to be able to build this easily

I think the latest PolyHook2`s CMake List is incorrect I cant see PolyHook_2.dll in the txt

**Comment by Ochii** [comment]
Can you try running ```setuplibs.ps1``` again?

**Comment by herowudi** [comment]
> Can you try running `setuplibs.ps1` again?

I really tried at least 10 times I changed a PC to try too the result is can`t find PolyHook_2.dll I think it didn`t be built

**Comment by herowudi** [comment]
> Can you try running `setuplibs.ps1` again?

PolyHook_2.lib

**Comment by Ochii** [comment]
Do you see PolyHook in your Visual Studio solution? ([example](https://puu.sh/C3B72/d4bb8b867a.png))

**Comment by herowudi** [comment]
> Do you see PolyHook in your Visual Studio solution? ([example](https://puu.sh/C3B72/d4bb8b867a.png))

I see,then I tried to built it there, there is some error in catch.cpp then building failed

**Comment by herowudi** [comment]
> Do you see PolyHook in your Visual Studio solution? ([example](https://puu.sh/C3B72/d4bb8b867a.png))

![image](https://user-images.githubusercontent.com/30003227/48668216-3e83ae00-eb23-11e8-89ba-1124b0195689.png)

**Comment by herowudi** [comment]
> Do you see PolyHook in your Visual Studio solution? ([example](https://puu.sh/C3B72/d4bb8b867a.png))

a lot of undefined

**Comment by herowudi** [comment]
> Do you see PolyHook in your Visual Studio solution? ([example](https://puu.sh/C3B72/d4bb8b867a.png))

Can you give me a project that has built the libraries？？Thank you very much

**Comment by Ochii** [comment]
Could you run ```setuplibs.ps1``` and send the console output here? Use a platform like [hastebin](https://hastebin.com/) to upload it, please

**Comment by Ochii** [comment]
I'm closing this since AppVeyor builds it fine and that the OP hasn't replied in a month

**Comment by felixabi** [comment]
Can you give me the .sln file?

**Comment by Ochii** [comment]
> Can you give me the .sln file?

You can generate a solution with CMake. See ["Starting the build"](https://github.com/Ochii/cso2-launcher#starting-the-build)

**Comment by felixabi** [comment]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x86\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc142.pdb" /Gd /TP /analyze- /FC /errorReport:queue "CMakeCXXCompilerId.cpp"
  CMakeCXXCompilerId.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x86\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdCXX.lib" /MACHINE:X86 /SAFESEH "Debug\CMakeCXXCompilerId.obj"
LINK : fatal error LNK1181: 'kernel32.lib' can't open input file [E:\cso2-launcher-0.4.1\CMakeFiles\3.14.19060802-MSVC_2\CompilerIdCXX\CompilerIdCXX.vcxproj]
"E:\cso2-launcher-0.4.1\CMakeFiles\3.14.19060802-MSVC_2\CompilerIdCXX\CompilerIdCXX.vcxproj" Project Completed (default targets) - FAILED.

Creation failed

PS E:\cso2-launcher-0.4.1> cmake -G "Visual Studio 16 2019" ./
-- Selecting Windows SDK version  to target Windows 10.0.18362.
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "E:/cso2-launcher-0.4.1/CMakeFiles/CMakeOutput.log".
See also "E:/cso2-launcher-0.4.1/CMakeFiles/CMakeError.log".

fatal error LNK1181: 'kernel32.lib' can't open input file[E:\cso2-launcher-0.4.1\CMakeFiles\3.14.19060802-MSVC_2\CompilerIdCXX\CompilerIdCXX.vcxproj]

what is this?

**Comment by felixabi** [comment]
what is missing?

**Comment by Ochii** [comment]
> what is missing?

Looks like the MSVC tools aren't in your path.

Try to using CMake in the "x86 Native Tools Command Prompt", found in the Windows menu, or run `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat` in a command prompt

**Comment by felixabi** [comment]
I would have a question
link to game from site button Is it possible to perform an automatic login function?

**Comment by felixabi** [comment]
link to game from site button Is it possible to perform an automatic login function?

**Comment by Ochii** [comment]
> link to game from site button Is it possible to perform an automatic login function?

Not at the moment

**Comment by felixabi** [comment]
I kept you here. sorry :) XD

**Comment by felixabi** [comment]
**********************************************************************
** Visual Studio 2019 Developer PowerShell v16.2.5
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
PS E:\CSO2LauncherS> cmake -G "Visual Studio 16 2019" ./
-- The CXX compiler identification is MSVC 19.22.27905.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- User did not specify build type, defaulting to Release build
CMake Error at CMakeLists.txt:20 (message):
  The launcher must be built for 32 bit platforms.


-- Configuring incomplete, errors occurred!
See also "E:/CSO2LauncherS/CMakeFiles/CMakeOutput.log".
PS E:\CSO2LauncherS>
