### ISSUE TITLE
How to use command in the debug console?

### ISSUE THREAD

**Issue by StarFox646** [Ochii/cso2-launcher#15]
https://www.youtube.com/watch?v=ffuU1baJQms

I saw this guy's video using console to start a game 

I've tried to use listmaps or listgamemodes commands like he did  but it didn't work. Anyone can help me out plz.

**Comment by w123456w30w** [comment]
you need masterserver

**Comment by StarFox646** [comment]
> you need masterserver

I've used the master server to host match successfully, I've got no problem hosting a game but I can't use the Debug Console thing to type the command that he use in the video.

**Comment by Ochii** [comment]
That feature was removed

**Comment by StarFox646** [comment]
I want to ask one more thing. So every time a match ended I can't get back to the manual, it stuck at the result screen, do you know how to fix it?

**Comment by Ochii** [comment]
@StarFox646 Not at the moment. You can check the progress of that issue [here](https://github.com/Ochii/cso2-master-server/issues/12)

**Comment by StarFox646** [comment]
Why did you remove the command feature though, it is very useful for spawning guns and adding bots. Anyway thank you for your reply :)
