### ISSUE TITLE
Can someone explain the instalation process for me?

### ISSUE THREAD

**Issue by RedLightPumpkin** [Ochii/cso2-launcher#17]
As the name says, Im having trouble following the instructions, could anyone more experienced help a newbie?

**Comment by Ochii** [comment]
Sure, what don't you understand?

**Comment by RedLightPumpkin** [comment]
how to actually make the game works, the main menu comes up, but im unsure if any of the play options should work, but they just chrash the game

**Comment by Ochii** [comment]
when you get to the main menu, press the *커스텀모드* option to open the channel list. this is the only option that works properly at the moment

**Comment by RedLightPumpkin** [comment]
also, when I try to log in, giving a nickname and random password, it chrashes

**Comment by Ochii** [comment]
Looks like the user name cannot exceed the 10 characters. Try using a smaller one. I'll put a warning in the readme

**Comment by RedLightPumpkin** [comment]
Alright, any password requirements?

**Comment by Ochii** [comment]
the username must use alphanumerical characters only aswell

**Comment by RedLightPumpkin** [comment]
Seems I can't find the folder you're talking about. You think that's even possible?

**Comment by Chinayangzhihong** [comment]
> 尝试清洁HKEY_CURRENT_USER \耐克森\ cso2 \ \软件设置

能加下你的QQ吗。 我有事情想找你 - -

**Comment by RedLightPumpkin** [comment]
Okay, I did find the folder, cleaned it, but any password I gave still chrashes the game.

**Comment by RedLightPumpkin** [comment]
Im using Windows 10 (Enterprise lol), my language is Polish

**Comment by GEEKiDoS** [comment]
> Also @GEEKiDoS have you had this issue before? I can't recreate this problem

Yes, but after clean that registry folder and using one character like "0" this issue fixed for me

**Comment by GEEKiDoS** [comment]
> Im using Windows 10 (Enterprise lol), my language is Polish

Enterprise 2019 LTSC here

**Comment by RedLightPumpkin** [comment]
@Ochii I guess that's the problem, I have it downloaded but I don't really know how to launch it

**Comment by Ochii** [comment]
Since OP didn't reply, I'll assume that the issue is fixed
