### ISSUE TITLE
Tier0.dll Error

### ISSUE THREAD

**Issue by L1nkle** [Ochii/cso2-launcher#19]
can't not found tier0.dll in my PC,sry I'm chinese so hard to tell what it's like in Englishi,even I copy the tier0.dll from Bin folder and Paste it to SysWOW64,it still error
无法定位程序输入点ThreadWaitForObjects 于动态链接库 tier0.dll上

**Comment by Ochii** [comment]
Since you're commenting other issues, I'll assume you have fixed this. If this is wrong, I'll reopen this
