### ISSUE TITLE
Add a custom path for modding cso2

### ISSUE THREAD

**Issue by GEEKiDoS** [Ochii/cso2-launcher#21]
It's a nice feature I guess?

**Comment by GEEKiDoS** [comment]
The gameinfo of cso2 is hardcoded in filesystem.dll at 0xFD6A8, Im going to try replace it

**Comment by GEEKiDoS** [comment]
snd_rebuildaudiocache is not working for custom sound

**Comment by GEEKiDoS** [comment]
Notes(Tested stuffs):
1. This method will sideload almost of game assets from custom folder.
2. uncompressed VTFs and decrypted eTXTs(not tried other formats like eCSV) will loaded by game.
3. Counter-Strike: Source or HL2 format BSPs won't load on CSO2 engine(no error, but the progress bar will stuck at 0% forever) 
......

**Comment by organnerx** [comment]
Hello! Some questions: 1. Is it possible to translate game interface and options (settings)? 2. Is it possible to use voice files and english text from Chinese version? Their characters are speaking English and also as far as I remember when you press radio buttons (z, x, c) all text and voicing there also in English (enemy spotted, need backup, etc...). This could be helpful for teamplay when you know what to report to others, rather than Korean writings and voices. Please take a look at possibility of those features

**Comment by GEEKiDoS** [comment]
> Hello! Some questions: 1. Is it possible to translate game interface and options (settings)? 2. Is it possible to use voice files and english text from Chinese version? Their characters are speaking English and also as far as I remember when you press radio buttons (z, x, c) all text and voicing there also in English (enemy spotted, need backup, etc...). This could be helpful for teamplay when you know what to report to others, rather than Korean writings and voices. Please take a look at possibility of those features

Translate game interface and option already working in current release version. check ```-lang``` argument

**Comment by organnerx** [comment]
I don't have a client to check how -lang argument. But I think you misunderstood me a bit. I mean complete interface translation - all room options that can be seen on your screenshot above and ingame radios and character voicing and etc. That could be a good addition to the game. Of course this is not priority number one in development, this just could be helpful and more attractive to a new players.

There is a file in game files called "resource/cso2_koreana.txt" witch holding all ingame text. And this is the only translation file that basic game contains. And there is no english in it. So I assume -lang not doing a great translation. We can edit this .txt with English text (at least basic interface and menus strings), but can we force a game to use our updated file? This is the main question. If we can force game to use that, than we can translate a game completely

**Comment by GEEKiDoS** [comment]
> I don't have a client to check how -lang argument work. But I think you misunderstood me a bit. I mean complete interface translation - all room options that can be seen on your screenshot above and ingame radios and character voicing and etc. That could be a good addition to the game. Of course this is not priority number one in development, this just could be helpful and more attractive to a new players.
> 
> There is a file called "resource/cso2_koreana.txt" witch holds all ingame text. And this is the only translation file that basic game archives contains. And there is no english in it. So I assume -lang not doing a great translation. We can edit this .txt with English text (at least basic interface and menus strings), but can we force a game to use our updated file? This is the main question. If we can force game to use that, than we can translate a game completely

What does ```-lang``` do is replace the cso2_koreana.txt. for example, if you translate the cso2_koreana.txt to english, then you can name it ```cso2_english.txt```, then place it in the ```Data/cstrike/resource/```. And then start the game with ```-lang english```. The game will load the ```cso2_english.txt``` instead of ```cso2_koreana.txt```, that's what it do.

**Comment by organnerx** [comment]
Ok, now I got it, thanks. Btw do you know is somebody working on a translation already? Or should I start making it by myself?

**Comment by Ochii** [comment]
Pull request #22 has been merged into master

**Comment by LucaSoranota** [comment]
so in order to use custom/mods i need to decrypt the whole game?
or just add args to read decrypted files?

**Comment by GEEKiDoS** [comment]
> so in order to use custom/mods i need to decrypt the whole game?
> or just add args to read decrypted files?

If yout just want to replace some of decrypted files, you just need to use ```-enablecustom`` to enable the ```custom``` folder to place the files(See https://github.com/Ochii/cso2-launcher/issues/21#issuecomment-460147890).  If you wanna decrypt whole filesystem then remove pkgs in Data(expect ```1b87c6b551e518d11114ee21b7645a47.pkg```), You just use ```-decryptedfiles``` instead.

**Comment by Riseless** [comment]
> so in order to use custom/mods i need to decrypt the whole game?
> or just add args to read decrypted files?
> 
> If yout just want to replace some of decrypted files, you just need to use -enablecustom to enable the custom folder to place the files(See #21 (comment)).
> If you wanna decrypt whole filesystem then remove pkgs in Data(expect 1b87c6b551e518d11114ee21b7645a47.pkg), You just use -decryptedfiles instead.

unpack all pkgs and remove they except 1b87c6b551e518d11114ee21b7645a47.pkg, and game give me this error
![default](https://user-images.githubusercontent.com/47669746/52868425-5c79a280-3154-11e9-85a6-3a5a2c3511fa.jpg)

**Comment by Ochii** [comment]
If you use UnCSO2 to unpack the files, it's broken at the moment. See [UnCSO2/#3](https://github.com/Ochii/UnCSO2/issues/3)

**Comment by enesvtn** [comment]
I didn't find what extension file needed to translate Sound and Interface Language in the game?
