### ISSUE TITLE
The client is terminated if the personal training mode is to be played.

### ISSUE THREAD

**Issue by DebugBios** [Ochii/cso2-launcher#23]
In some cases, the execution process ends at the same time.

Shut down to use the bot_add console.

**Comment by DebugBios** [comment]
![default](https://user-images.githubusercontent.com/44349391/52337303-a5da3b80-2a4a-11e9-9791-68ca0118d0aa.PNG)
![2](https://user-images.githubusercontent.com/44349391/52337305-a5da3b80-2a4a-11e9-8d96-e4bc6a764258.PNG)
The graphics are also broken in playroom mode.

**Comment by Ochii** [comment]
Is the issue gone for you in [build 0.2.1](https://github.com/Ochii/cso2-launcher/releases/tag/Build-0.2.1-0e9ff5be-master)?

**Comment by lisigang1994** [comment]
thanks ochii. I think my question before is the same. add bot or after several matches may cause disconnect from the server.I ll have a try of new launcher tonight

**Comment by DebugBios** [comment]
@Ochii The problem has disappeared. Thank you!
