### ISSUE TITLE
The new build launcher caused vram leak

### ISSUE THREAD

**Issue by GEEKiDoS** [Ochii/cso2-launcher#24]
The game crashes or texture/ui images not loading.

Lot of people had this issue, not my problem.

Both Build 0.2.0-62199858-master and Build 0.2.0-3f93e707-master had this issue

**Comment by Ochii** [comment]
I tested 62199858 and I don't have any issues. How do I reproduce this?

**Comment by GEEKiDoS** [comment]
> I tested [6219985](https://github.com/Ochii/cso2-launcher/commit/621998587ee796cb99611b8379e0a110bc572280) and I don't have any issues. How do I reproduce this?

That's wired, I tried again, this issue is gone. but here's the screenshot of that problem/
![qq 20190209022643](https://user-images.githubusercontent.com/14933408/52497880-3616ad00-2c12-11e9-8873-663c8bede77a.jpg)
![qq 20190209022647](https://user-images.githubusercontent.com/14933408/52497881-3747da00-2c12-11e9-8d90-da3ab036e97e.png)
![qq 20190209022652](https://user-images.githubusercontent.com/14933408/52497884-37e07080-2c12-11e9-8fba-22bd44508196.jpg)
![wg9 k uvakq v 5cy ts2do](https://user-images.githubusercontent.com/14933408/52497885-38790700-2c12-11e9-9baf-4448b7595e97.png)

**Comment by GEEKiDoS** [comment]
Too hard to reproduce, so I'm closing this.

**Comment by GEEKiDoS** [comment]
> I tested [6219985](https://github.com/Ochii/cso2-launcher/commit/621998587ee796cb99611b8379e0a110bc572280) and I don't have any issues. How do I reproduce this?

I reproduced this once with 6219985, this guy got this error many times
![qq 20190209023659](https://user-images.githubusercontent.com/14933408/52498435-c0134580-2c13-11e9-8870-f8ef5fb06c95.png)

He says after upgrading launcher to 3f93e707, His game crashed with both Chinese or Korean language. After the 6219985 build pushes, he downloaded again and got red textures like pictures in https://github.com/Ochii/cso2-launcher/issues/24#issuecomment-461898944, then he back to 1.4 builds without any errors.

Others also posted some similar pictures to me, So I raised a issues here

**Comment by DebugBios** [comment]
#23 
It seems to be the same as the issue. In some modes, the sky box disappears or a graphic crash occurs.

**Comment by Ochii** [comment]
CMake doesn't add /LARGEADDRESSAWARE in the linker flags, that could be the issue. I'll update master with /LARGEADDRESSAWARE enabled
