### ISSUE TITLE
is it possible to save user's own data?

### ISSUE THREAD

**Issue by L1nkle** [Ochii/cso2-launcher#25]
I have tried to play with my friend by P2P,is very good,but sometimes it have a little bit unstable,lost connection to the server or something,if we have these issues,is not a big deal,we can rejoin the game then play it,but my friend thought is very annoying to re-edit the inventory and buy menu,we have tried to change language and is pretty much a little bit problem too,thread error will apear most of the time,he have to restart the game a lot's of time,so I want to ask,is this problem from game's master server's own or our P2P problem?and we want to ask is it possible to let the game save player or server master's own data,such as buy menu setting and charater or anything like that,we'd very love this game and very nice to see you let the game come back if we're using P2P or VPN to play it with our friend,hope you do better and I will reply you more BUGs and problems to you once we found these

**Comment by GEEKiDoS** [comment]
That's possible. And can you segment your words? It's too hard to read them.

I prefer save the userdata in user side if playing in lan enviroment.

**Comment by L1nkle** [comment]
> That's possible. And can you segment your words? It's too hard to read them.
> 
> I prefer save the userdata in user side if playing in lan enviroment.

yes,we found user saving data in server folder,user.js is the user's saving data,but it's on server side,by the way,can we keep in touch with each others?we're keep changing the game's source code,my friend found if the sv_cheats keep it at 1,it will get loss to master server and player,so we're finding way to shut sv_cheats off

**Comment by L1nkle** [comment]
> That's possible. And can you segment your words? It's too hard to read them.
> 
> I prefer save the userdata in user side if playing in lan enviroment.

oh by the way,I felt sorry about the segments,I will notice it next time,sry about that

**Comment by organnerx** [comment]
+1 to topic starter. It is so annoying to reedit an inventory completely. There should be a feature to save user data on server side by the login name (because there can be 2 players with the same ip) or on the client side. Please implement this

**Comment by L1nkle** [comment]
> +1 to topic starter. It is so annoying to reedit an inventory completely. There should be a feature to save user data on server side by the login name (because there can be 2 players with the same ip) or on the client side. Please implement this

we're finding way to do it,but we found it's pretty hard to do,so we'd love to hear about how Ochii think and do,if we can,we will did it asap,but now the biggest problem for us is the LAN Packets Loss

**Comment by Ochii** [comment]
I plan on using MongoDB to store user information, including the inventory and loadouts

**Comment by L1nkle** [comment]
> I plan on using MongoDB to store user information, including the inventory and loadouts

ok thanks about it,I think we met a BUG,if sv_cheats keep it on,other user will have Packets Loss,is it server side's problem or just P2P Glitch?

**Comment by Ochii** [comment]
Do you have that problem in [version 0.2.2](https://github.com/Ochii/cso2-launcher/releases/tag/Build-0.2.2-6e7fd504-master)? @GEEKiDoS applied some fixes about sv_cheats

**Comment by GEEKiDoS** [comment]
> > I plan on using MongoDB to store user information, including the inventory and loadouts
> 
> ok thanks about it,I think we met a BUG,if sv_cheats keep it on,other user will have Packets Loss,is it server side's problem or just P2P Glitch?

Try latest launcher, I should patched thoese traps

**Comment by L1nkle** [comment]
> @L1nkle do you have that problem in [version 0.2.2](https://github.com/Ochii/cso2-launcher/releases/tag/Build-0.2.2-6e7fd504-master)? @GEEKiDoS applied some fixes about sv_cheats

I have tried to shut off cheats in Studio 17 with version 0.2.0,Packets Loss has improve a lot,thanks a lots,I will update launcher later

**Comment by Ochii** [comment]
I'm closing this. If you want to discuss the database discussion feel free to open an issue at the [cso2-master-server's repo](https://github.com/Ochii/cso2-master-server)
