### ISSUE TITLE
Unable to start the game and graphics problems

### ISSUE THREAD

**Issue by w123456w30w** [Ochii/cso2-launcher#26]
![image](https://user-images.githubusercontent.com/30130993/52519277-c2b57f80-2c93-11e9-844f-49afb3c65643.png)
![image](https://user-images.githubusercontent.com/30130993/52519299-3061ab80-2c94-11e9-88f0-d3cc8f4f7140.png)

Crashlog:
17:58:37	D3D9Ex State [5]
17:58:37	[NVIDIA GeForce RTX 2080 Ti] [VID:0x000010de] [DID:0x00001f07] [Riv:0x000000a1] [Dx:95/95] [DVer:0x00190015/0x000e0759]
17:58:37	[Query] Update queued con vars.
17:58:52	VideoMode shutdown
17:58:52	VideoMode :Released Full Screen 
17:58:52	Detach from window 
17:58:52	Destroy window 
17:58:52	unload unicode
17:58:52	VideoMode :Destroyed Game Window

**Comment by KikoTs** [comment]
Did you update to the newest version of the launcher ?

**Comment by w123456w30w** [comment]
> Did you update to the newest version of the launcher ?

I compiled it with the latest commit

**Comment by w123456w30w** [comment]
graphics error update
![image](https://user-images.githubusercontent.com/30130993/52519884-3b6d0980-2c9d-11e9-8d88-17c390370c00.png)

**Comment by Ochii** [comment]
That's a weapon exclusive to China's CSO2, I believe. Its texture files are not in the Korean's CSO2 game files

I'm closing this since you can start the game with no problems
