### ISSUE TITLE
The winsocket problem still exist for me.......

### ISSUE THREAD

**Issue by lisigang1994** [Ochii/cso2-launcher#27]
I don't know if only me have this problem. That's my case: If I start a private room, add some bot(not by console) then finish the match and repeat this several times,（start about 4 bots rooms） must cause the game disconnect from the server. I have tried this on other computers and the results are same. If anyone has the same problem or knows something about it, thanks for sharing.

**Comment by Ochii** [comment]
Duplicate of #20. I'll put your post in there
