### ISSUE TITLE
Internal console?

### ISSUE THREAD

**Issue by GEEKiDoS** [Ochii/cso2-launcher#28]
The external console is too annoying.
I'm trying to make a internal one with ImGui.

![nte o vyf0 8 d 3zfnf350](https://user-images.githubusercontent.com/14933408/52524158-efd65200-2cd4-11e9-9b46-9fb8595bd228.png)

How do you guys think about it.  or can you guys get original console working?

And how should I make something like auto complete.

**Comment by Ochii** [comment]
it looks good. the original console (vgui one) can be reenabled, but you can't use it in the main menu. It's also behind Scaleform

**Comment by JusicP** [comment]
> It looks good. the original console (vgui one) can be reenabled, but you can't use it in the main menu. It's also behind Scaleform. I haven't tried to make it work
> 
> EDIT: here's a screenshot with it enabled
> ![ss](https://user-images.githubusercontent.com/4953934/52525438-986abe80-2ca1-11e9-9479-7f10daf44baa.png)

Try to set another parent for console panel

**Comment by Ochii** [comment]
Merged in 0.3.0
