### ISSUE TITLE
tier0.dll plz help me 

### ISSUE THREAD

**Issue by darknessmaddog** [Ochii/cso2-launcher#30]
I download the tier0.dll from a website and Paste it to SysWOW64 and system32. It show this to me when I startEd the cso2-start.bat. 

Launcher.exe 無法找到輸入點
Launcher.exe could not find the entry point

無法找到程序輸入點 ?AddMsg@CSO2DocumentLog@@QAAXHPBDZZ (在動態連結程式庫 tier0.dll)
Could not find program entry point ?AddMsg@CSO2DocumentLog@@QAAXHPBDZZ (in the dynamic link library tier0.dll)

I am Taiwanese my English is very bad

**Comment by Ochii** [comment]
open cso2_nexon_v22406 with 7zip. winrar doesn't work sometimes

**Comment by darknessmaddog** [comment]
Cmd indicate 
“Launcher.exe” 不是內部或外部命令，可執行的程式或批次檔
"Launcher.exe" is not an internal or external command, executable program or batch file
Then it Disappear quickly

**Comment by Ochii** [comment]
Which files are in your game folder?

**Comment by darknessmaddog** [comment]
https://drive.google.com/file/d/1y0diL2nTERlOaJZQTA3xPb8owx82GjtB/view
https://github.com/Ochii/cso2-launcher/releases?utm_source=Facebook_PicSee
This and this

**Comment by darknessmaddog** [comment]
https://drive.google.com/file/d/1pR4R41COjcKuVEdpwn5wdYtT-_hkaHzm/view 
And this in the Data(cstrike)

**Comment by Ochii** [comment]
Do you get that error when you run `startcso2.bat`?

**Comment by GEEKiDoS** [comment]
你能把你的絕對武力Online 2路徑下的bin目錄的内容截圖一下嗎？ Launcher.exe和startcso2.bat文檔是需要放在bin目錄下的，如果放在bin目錄下還是出現了tier0.dll找不到的問題 説明你的文件時損壞的。

以及請不要將網上下載下來的tier0.dll放到system32以及syswow64目錄内，這是沒有用的，而且有時候會引發別的問題，tier0是游戲裏的不是運行庫的。

**Comment by darknessmaddog** [comment]
https://drive.google.com/file/d/1QVGz8E4EYZrRjyyb44nSI10CoIQ1_sSf/view?usp=drivesdk
截圖我放在雲端
Photo in the google

**Comment by GEEKiDoS** [comment]
> https://drive.google.com/file/d/1QVGz8E4EYZrRjyyb44nSI10CoIQ1_sSf/view?usp=drivesdk
> 截圖我放在雲端
> Photo in the google

将文件放入bin文件夹即可，像这样：
![qq 20190213003043](https://user-images.githubusercontent.com/14933408/52651155-a1b88d00-2f26-11e9-9a41-f8623c2003e2.jpg)

**Comment by darknessmaddog** [comment]
I fix it thanks everyone
