### ISSUE TITLE
Sound replace bug.

### ISSUE THREAD

**Issue by Riseless** [Ochii/cso2-launcher#34]
I replace all radio sounds with clear soundcache file, and got this error. 
https://youtu.be/cE-MoWY37HU

**Comment by organnerx** [comment]
If you followed this tutorial https://github.com/Ochii/cso2-launcher/issues/21#issuecomment-460213422 then there is a typo. You should create empty not 'allsound.cache' but 'allsounds.cache'. Then it will work

**Comment by Riseless** [comment]
it works. Thanks
