### ISSUE TITLE
Launcher is not the correct win32 program

### ISSUE THREAD

**Issue by darknessmaddog** [Ochii/cso2-launcher#37]
My friend ask
launcher不是正確的win32程式
Launcher is not the correct win32 program
How to fix it?

**Comment by organnerx** [comment]
Check if your windows is x64 system. This error happens if your system is not fitting system requirements

**Comment by Ochii** [comment]
Could you edit your issue according to the new [issue templates](https://github.com/Ochii/cso2-launcher/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)?

**Comment by Ochii** [comment]
@darknessmaddog did you fix this?

**Comment by darknessmaddog** [comment]
He fixed. Thank you very much!
