### ISSUE TITLE
Can't join a match

### ISSUE THREAD

**Issue by gnexia2013** [Ochii/cso2-launcher#43]
Why is it that when I'm playing, everyone is online, and then the host can play the game, and when someone else loads it to 15% or 10%, it gets stuck and can't get into the game?
How can I solve this problem?

**Comment by Ochii** [comment]
Send the `cso2_report_log.txt` log file and the output from the master server here

**Comment by gnexia2013** [comment]
cso2_report_log
16:15:52	Init FS ###00
16:15:52	Init FS ###10
16:15:52	Init FS ###20
16:15:52	Init FS ###30
16:15:52	Init FS ###40
16:15:52	Init FS ###50
16:15:52	Init FS ###60
16:15:52	Init FS ###70
16:15:52	Init FS ###80
16:15:52	Init FS ###90
16:15:52	Init FS ###100
16:15:53	Init FS ###110
16:15:53	D3D9Ex State [5]
16:15:53	[NVIDIA GeForce GTX 960] [VID:0x000010de] [DID:0x00001401] [SID:0x32011462] [Riv:0x000000a1] [Dx:95/95] [DVer:0x00190015/0x000e06eb]
16:15:53	[Query] Update queued con vars.
16:15:54	-Release Resources [C:0] [R:7]
16:15:54	+Reacquire Resources [C:1] [R:-]
16:15:54	NMStage[112] - 
16:16:15	started HpLT 
16:16:15	[Query] Material configs are changed.
16:16:15	-Release Resources [C:0] [R:7]
16:16:15	+Reacquire Resources [C:1] [R:-]
16:16:16	NMStage[113] - 
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$fontSystemTextOver28' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$fontNormalText' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$fontNormalTitleText' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$fontSystemText' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$normalKor' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$fontNumber' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$fontKill' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$fontSystemTextOver28' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$fontSystemTextOver28' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$fontNormalText' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$fontNormalTitleText' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$fontSystemText' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$normalKor' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$fontNumber' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$fontKill' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$fontSystemTextOver28' already mapped
16:16:18	Gfx Error : FontMap::MapFont failed - font name '$fontSystemTextOver28' already mapped
16:16:18	Gfx Error : HALInitParams::RenderThreadId is NULL - assuming current thread is the render thread.
16:16:19	-Release Resources [C:0] [R:7]
16:16:19	+Reacquire Resources [C:1] [R:-]
16:16:19	Shadow [-1->3]
16:16:19	-Release Resources [C:0] [R:7]
16:16:19	+Reacquire Resources [C:1] [R:-]
16:16:21	NMStage[114] - 
16:16:22	NMStage[115] - 
16:16:22	[Query] EnterLobby
16:16:23	NMStage[116] - 
16:16:23	NMStage[117] - 
16:16:23	NMStage[118] - 
16:16:23	Start Log - [ Texture:-1 / LOD:0 / Shader:1 / Shadow:3 ]
16:16:23	-Release Resources [C:0] [R:7]
16:16:23	+Reacquire Resources [C:1] [R:-]
16:16:26	-Release Resources [C:0] [R:7]
16:16:26	+Reacquire Resources [C:1] [R:-]
16:16:35	NMStage[119] - Auth OK
16:16:35	NMStage[120] - Connected to GatewayServer
16:16:36	my nickname - lc6154
16:16:36	NMStage[121] - arrived serverList stage
16:16:50	Enter room. Initialize room members.
16:16:50	Set Host : 2
16:17:06	Set Host : 2
16:17:06	Received Host Join. IsReconnect = 0 
16:17:06	[Query] EnterGame
16:17:06	Connection Command - [arg] map : ZD_ITALY ip:123.179.204.223:2132 oid:2 myoid:3 mod:Z_SCENARIO_SIDE
16:17:06	Host is Hole Punched
16:17:06	Base client state disconnected. Reason : Connecting to remote host
16:17:06	PrepairHostCrash Start.
16:17:14	PrepairHostCrash End.
16:17:14	Try connect to ... 123.179.204.223:2132
16:17:14	Connect to 123.179.204.223:2132 ... 
16:17:14	Connecting to 123.179.204.223:2132...
16:17:14	Get challenge IsRelay : 0, OID: 2
16:17:20	Retrying 123.179.204.223:2132...
16:17:20	Get challenge IsRelay : 0, OID: 2
16:17:26	Retrying 123.179.204.223:2132...
16:17:26	Get challenge IsRelay : 0, OID: 2
16:17:32	Retrying 123.179.204.223:2132...
16:17:32	Get challenge IsRelay : 0, OID: 2
16:17:38	Retrying 123.179.204.223:2132...
16:17:38	Get challenge IsRelay : 0, OID: 2
16:17:44	Retrying 123.179.204.223:2132...
16:17:44	Get challenge IsRelay : 0, OID: 2
16:17:50	Retrying 123.179.204.223:2132...
16:17:50	Get challenge IsRelay : 0, OID: 2
16:17:56	Retrying 123.179.204.223:2132...
16:17:56	Get challenge IsRelay : 0, OID: 2
16:18:02	Retrying 123.179.204.223:2132...
16:18:02	Get challenge IsRelay : 0, OID: 2
16:18:08	Retrying 123.179.204.223:2132...
16:18:08	Get challenge IsRelay : 0, OID: 2
16:18:14	Connection failed after 10 retries. Retry count = 10
16:18:14	Base client state disconnected. Reason : Connection failed
16:18:14	[Query] EnterLobby
16:18:14	Connection failed. State is none.
16:18:14	Host Disconnect reason : Disconnect reason : goto in room
16:18:14	Base client state disconnected. Reason : Disconnect reason : goto in room
16:18:14	Base client state disconnected. Reason : Connection fail to host
16:18:14	hs::s_gs - cur:7, nxt:7 
16:18:14	hs::s_gs - ServerGame LevelShutdown
16:18:14	hs::s_gs - ActivateMouse
16:18:14	hs::s_gs - GameShutdown
16:18:14	Host_ShutdownServer
16:18:15	Flush Pended Uncache Texture
16:18:15	Flush AnimBlock
16:18:15	hs::s_gs - end
16:18:27	OnSystemExit s:2 c:2
16:18:27	hs::s_gs - cur:7, nxt:8 
16:18:27	hs::s_gs - ServerGame LevelShutdown
16:18:27	hs::s_gs - GameShutdown
16:18:27	Flush Pended Uncache Texture
16:18:27	Flush AnimBlock
16:18:27	hs::s_gs - end
16:18:27	finished HpLT 
16:18:27	Host Disconnect reason : Disconnect reason : Host shutdown
16:18:27	Base client state disconnected. Reason : Disconnect reason : Host shutdown
16:18:32	VideoMode shutdown
16:18:32	VideoMode :Released Full Screen 
16:18:32	Detach from window 
16:18:32	Destroy window 
16:18:32	unload unicode
16:18:32	VideoMode :Destroyed Game Window 
16:18:32	socket manager closed server : called by destructor

16:18:32	last server - ip:156.236.70.205 port:30001
16:18:32	Try socket closing.
16:18:32	Clear buffer.
16:18:32	SSL closed.
16:18:32	Try socket closing.
16:18:32	Clear buffer.
16:18:32	SSL closed.

**Comment by gnexia2013** [comment]
output from the master server here
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle cso2-master-server@0.8.9~prestart: cso2-master-server@0.8.9
6 info lifecycle cso2-master-server@0.8.9~start: cso2-master-server@0.8.9
7 verbose lifecycle cso2-master-server@0.8.9~start: unsafe-perm in lifecycle true
8 verbose lifecycle cso2-master-server@0.8.9~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Administrator\Desktop\2231~\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle cso2-master-server@0.8.9~start: CWD: C:\Users\Administrator\Desktop\2231~
10 silly lifecycle cso2-master-server@0.8.9~start: Args: [ '/d /s /c', 'node dist/server.js' ]
11 silly lifecycle cso2-master-server@0.8.9~start: Returned: code: 3221225786  signal: null
12 info lifecycle cso2-master-server@0.8.9~start: Failed to exec start script
13 verbose stack Error: cso2-master-server@0.8.9 start: `node dist/server.js`
13 verbose stack Exit status 3221225786
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid cso2-master-server@0.8.9
15 verbose cwd C:\Users\Administrator\Desktop\2231~\dist
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 3221225786
22 error cso2-master-server@0.8.9 start: `node dist/server.js`
22 error Exit status 3221225786
23 error Failed at the cso2-master-server@0.8.9 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221225786, true ]

**Comment by gnexia2013** [comment]
@Ochii

**Comment by Ochii** [comment]
do you know if the host has its NAT open?

**Comment by gnexia2013** [comment]
I don't know, but I used OPEN VPN to build an intranet and solve the problem.

**Comment by Ochii** [comment]
Alright, I'll close this then
