### ISSUE TITLE
Game cannot start

### ISSUE THREAD

**Issue by Ardibengu** [Ochii/cso2-launcher#45]
I open launcher_main.exe and it shows the cmd then nothing happens . 
It doesn't open the game please help!! 
![image](https://user-images.githubusercontent.com/47745030/53126179-72041900-3514-11e9-8b2b-b53b82463f5b.png)

**Comment by Ochii** [comment]
That's an old version of the launcher, try using [0.3.2](https://github.com/Ochii/cso2-launcher/releases/tag/Build-0.3.2)
