### ISSUE TITLE
-enablecustom not loading .lo files

### ISSUE THREAD

**Issue by organnerx** [Ochii/cso2-launcher#51]
If you use -enablecustom flag, it works fine, but it not loading .lo files to the game. Those files are compiled scripts. I tried to replace one mode with another to make two same modes. I renamed everything correctly, but game don't even trying to load my new .lo files and using old ones.

1. Go to 'custom\scripts\mod' and create for example folder 'z_scenario_side'.
2. Put in this folder, mode files from folder 'hide' and rename them into mod_z_scenario_side.lo and ui_z_scenario_side.lo.
3. Launch the game mode and it will start Z Crush Side instead of Hide'n'Seek without attempting to load new files.

Windows 7 (64 bit)

**Comment by GEEKiDoS** [comment]
.lo is not checked by IsFileEncrypted function, just encrypt them back with https://github.com/GEEKiDoS/CSO2Crypto

**Comment by organnerx** [comment]
> 
> 
> .lo is not checked by IsFileEncrypted function, just encrypt them back with https://github.com/GEEKiDoS/CSO2Crypto

Thank you for the tip. You program didn't work for me but I used uncso2 instead and it works fine. Screenshot of error if you interested: http://wohlnet.ru/sentfile/dgsada4e.png

**Comment by GEEKiDoS** [comment]
> > .lo is not checked by IsFileEncrypted function, just encrypt them back with https://github.com/GEEKiDoS/CSO2Crypto
> 
> Thank you for the tip. You program didn't work for me but I used uncso2 instead and it works fine. Screenshot of error if you interested: http://wohlnet.ru/sentfile/dgsada4e.png

Forget to let user input path in that program.
