### ISSUE TITLE
Error 3001

### ISSUE THREAD

**Issue by SergeMusoka** [Ochii/cso2-launcher#55]
Hi. Could you help me please? I've get error 3001 while loading map. It happens on 5%, after that the game is crashed. I tried the latest versions and it all show error messages. Interestingly, version 0.1.3 works fine.

**Comment by gnexia2013** [comment]
Hi. Could you help me please? I've get error 2004 while loading map. It happens on 10%,

**Comment by gnexia2013** [comment]
I rented a server, but others played on my server and loaded to %10.

**Comment by gnexia2013** [comment]
Is there RADMIN solution without this?

**Comment by gnexia2013** [comment]
Except, radmin,openvpn， is there no solution?

**Comment by SergeMusoka** [comment]
@gnexia2013 Try to turn off your antivirus and firewall.

**Comment by gnexia2013** [comment]
i Try to turn off antivirus and firewall.

**Comment by organnerx** [comment]
@gnexia2013. There is no solution because dedicated server is not made yet. So in order to play with everybody successfully, all players need to be in the same lan network.
