### ISSUE TITLE
Failed to load the launcher DLL

### ISSUE THREAD

**Issue by dmitrylc** [Ochii/cso2-launcher#6]
![errordll](https://user-images.githubusercontent.com/2939460/45590391-fa680780-b93f-11e8-871b-9d78a593d875.PNG)
I wanted to test the "launcher" on another computer. On the my main computer it works.

**Comment by Ochii** [comment]
This occurs because PolyHook uses runtime DLLs.

Try installing the [Visual Studio 2017 C++ Redist](https://aka.ms/vs/15/release/vc_redist.x86.exe) and building the project with the Release configuration

**Comment by dmitrylc** [comment]
Nothing has changed after installation

**Comment by Ochii** [comment]
Is your other computer using a release build? If it is then try cleaning the project and build again

**Comment by dmitrylc** [comment]
1. https://github.com/Ochii/cso2-launcher/tree/server_emulator
2. After updating the repository, I again downloaded a clean project. Nothing has changed.

**Comment by Ochii** [comment]
I should have asked you first, what error are you having? I am unable to understand Japanese so an error code would be helpful

**Comment by dmitrylc** [comment]
Here is the translation: The specified module could not be found.

**Comment by Ochii** [comment]
Can you run dependency walker or a similiar program on launcher.dll?

**Comment by dmitrylc** [comment]
This program? (Screenshot not mine)
![snapshot](https://user-images.githubusercontent.com/2939460/45616348-d9a2cd80-ba77-11e8-9035-f15e4f73831e.png)

**Comment by Ochii** [comment]
Yes. It should say which module is missing

**Comment by dmitrylc** [comment]
Here log file:
[launcher_dll.txt](https://github.com/Ochii/cso2-launcher/files/2388171/launcher_dll.txt)
[launcher_main_exe.txt](https://github.com/Ochii/cso2-launcher/files/2388174/launcher_main_exe.txt)
[PolyHook_2_dll.txt](https://github.com/Ochii/cso2-launcher/files/2388176/PolyHook_2_dll.txt)

**Comment by Ochii** [comment]
PolyHook_2.dll can't find either MSVCP140D.DLL, VCRUNTIME140D.DLL or UCRTBASED.DLL, which are debug libraries. Build the project in Release mode ([an example in Visual Studio 17](https://puu.sh/Bwq9n/899e53022b.png))

**Comment by dmitrylc** [comment]
![error](https://user-images.githubusercontent.com/2939460/45635687-5a7cbc00-baae-11e8-995a-cbadd57712e3.JPG)

**Comment by Ochii** [comment]
Did you run setuplibs.ps1?

**Comment by dmitrylc** [comment]
Yes

**Comment by Ochii** [comment]
Odd, AppVeyor is building it fine. Maybe try recloning the project again?

**Comment by Ochii** [comment]
You can get a fresh build [here](https://github.com/Ochii/cso2-launcher/releases/latest)

**Comment by Ochii** [comment]
Hey, could you try the [new build](https://github.com/Ochii/cso2-launcher/releases/tag/v0.1.5-1)?

**Comment by Ochii** [comment]
The launcher is now a single module, this should no longer occur
