### ISSUE TITLE
Unable to generate VS 2019 solution with CMake

### ISSUE THREAD

**Issue by Ochii** [Ochii/cso2-launcher#70]
**********************************************************************
** Visual Studio 2019 Developer PowerShell v16.2.5
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
PS E:\CSO2LauncherS> cmake -G "Visual Studio 16 2019" ./
-- The CXX compiler identification is MSVC 19.22.27905.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- User did not specify build type, defaulting to Release build
CMake Error at CMakeLists.txt:20 (message):
  The launcher must be built for 32 bit platforms.

-- Configuring incomplete, errors occurred!
See also "E:/CSO2LauncherS/CMakeFiles/CMakeOutput.log".
PS E:\CSO2LauncherS>

_Originally posted by @felixabi in https://github.com/Ochii/cso2-launcher/issues/13#issuecomment-533845360_

**Comment by Ochii** [comment]
@felixabi 

Try `cmake -G  "Visual Studio 16 2019 -A Win32 ./".

You should know that I haven't tested the launcher in Visual Studio 2019

**Comment by felixabi** [comment]
okey

**Comment by felixabi** [comment]
cmake -G "Visual Studio 16 2019 -A Win32 ./" - this code did not work
cmake -G "Visual Studio 16 2019" -A Win32 ./ - i tried that


-- The CXX compiler identification is MSVC 19.22.27905.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- User did not specify build type, defaulting to Release build
-- The C compiler identification is MSVC 19.22.27905.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at libs/PolyHook_2_0/CMakeLists.txt:215 (add_subdirectory):
  The source directory

    E:/CSO2LauncherS1/libs/PolyHook_2_0/capstone

  does not contain a CMakeLists.txt file.


-- cotire 1.8.0 loaded.
CMake Error at launcher/CMakeLists.txt:241 (target_compile_options):
  Cannot specify compile options for target "capstone-static" which is not
  built by this project.


CMake Error at launcher/CMakeLists.txt:242 (target_link_options):
  Cannot specify link options for target "capstone-static" which is not built
  by this project.


-- CXX RC target launcher cotired without unity build.
-- Configuring incomplete, errors occurred!
See also "E:/CSO2LauncherS1/CMakeFiles/CMakeOutput.log".



CMakeOutput.log >
  Microsoft for x86 (R) C/C++ Enhanced Compiler Version 19.22.27905

  testCCompiler.c

  Copyright (C) Microsoft Corporation. All Rights Reserved.

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /Oy- /D "WIN32" /D "_WINDOWS" /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_9b3a8.dir\Debug\\" /Fd"cmTC_9b3a8.dir\Debug\vc142.pdb" /Gd /TC /analyze- /errorReport:queue E:\CSO2LauncherS1\CMakeFiles\CMakeTmp\testCCompiler.c

  cmTC_9b3a8.vcxproj -> E:\CSO2LauncherS1\CMakeFiles\CMakeTmp\Debug\cmTC_9b3a8.exe




Detecting C compiler ABI info compiled with the following output:
Change Dir: E:/CSO2LauncherS1/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_da80b.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=16.0 /v:m && .NET Framework için Microsoft (R) Build Engine Version 16.2.37902+b5aaefc9f

Copyright (C) Microsoft Corporation. All Rights Reserved.



  Microsoft for x86 (R) C/C ++ Enhanced Compiler Version 19.22.27905

  Copyright (C) Microsoft Corporation. All Rights Reserved.

  CMakeCCompilerABI.c

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /Oy- /D "WIN32" /D "_WINDOWS" /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_da80b.dir\Debug\\" /Fd"cmTC_da80b.dir\Debug\vc142.pdb" /Gd /TC /analyze- /errorReport:queue "C:\Program Files\CMake\share\cmake-3.15\Modules\CMakeCCompilerABI.c"

  cmTC_da80b.vcxproj -> E:\CSO2LauncherS1\CMakeFiles\CMakeTmp\Debug\cmTC_da80b.exe

**Comment by felixabi** [comment]
I installed Visual Studio 2017 and I can't find Powershell.

**Comment by felixabi** [comment]
and
Severity Code Description Project File Line Hide Status
Error CMake: E: \ CSO2LauncherS1 \ CMakeLists.txt: 20 (message):
The initiator must be created for 32-bit platforms. launcher E: \ CSO2LauncherS1 \ CMakeLists.txt 20

**Comment by Ochii** [comment]
Try running `git submodule update --recursive` in the project directory, then try generating the project files again

**Comment by felixabi** [comment]
PS E:\CSO2LauncherS2> git submodule update --recursive
PS E:\CSO2LauncherS2> cmake -G "Visual Studio 16 2019" -A Win32 ./
-- The CXX compiler identification is MSVC 19.22.27905.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- User did not specify build type, defaulting to Release build
-- The C compiler identification is MSVC 19.22.27905.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.22.27905/bin/Hostx64/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at libs/PolyHook_2_0/CMakeLists.txt:215 (add_subdirectory):
  The source directory

    E:/CSO2LauncherS2/libs/PolyHook_2_0/capstone

  does not contain a CMakeLists.txt file.


-- cotire 1.8.0 loaded.
CMake Error at launcher/CMakeLists.txt:241 (target_compile_options):
  Cannot specify compile options for target "capstone-static" which is not
  built by this project.


CMake Error at launcher/CMakeLists.txt:242 (target_link_options):
  Cannot specify link options for target "capstone-static" which is not built
  by this project.


-- CXX RC target launcher cotired without unity build.
-- Configuring incomplete, errors occurred!
See also "E:/CSO2LauncherS2/CMakeFiles/CMakeOutput.log".

**Comment by Ochii** [comment]
Can you send a list of files inside `E:/CSO2LauncherS2/libs/PolyHook_2_0/capstone`?

**Comment by felixabi** [comment]
thanks sln succes fix capstone

**Comment by felixabi** [comment]
Dear Ochii

![1](https://user-images.githubusercontent.com/36341134/65388977-a0233300-dd59-11e9-9378-7ba771770e5d.PNG)



![2](https://user-images.githubusercontent.com/36341134/65388974-9bf71580-dd59-11e9-990d-b24391c82339.PNG)



![3](https://user-images.githubusercontent.com/36341134/65388973-98638e80-dd59-11e9-83ba-59bb45019150.PNG)


![4](https://user-images.githubusercontent.com/36341134/65388957-7cf88380-dd59-11e9-84ba-06835a8c1480.PNG)

????????????????
Local Windows Debugger Click Error
