### ISSUE TITLE
Build Error Vector.h + console.cpp - Visual Studio 2019

### ISSUE THREAD

**Issue by felixabi** [Ochii/cso2-launcher#71]
Dear Ochii..

![1](https://user-images.githubusercontent.com/36341134/65388977-a0233300-dd59-11e9-9378-7ba771770e5d.PNG)

![2](https://user-images.githubusercontent.com/36341134/65388974-9bf71580-dd59-11e9-990d-b24391c82339.PNG)

![3](https://user-images.githubusercontent.com/36341134/65388973-98638e80-dd59-11e9-83ba-59bb45019150.PNG)

![4](https://user-images.githubusercontent.com/36341134/65388957-7cf88380-dd59-11e9-84ba-06835a8c1480.PNG)

????????????????

ERROR

**Comment by Ochii** [comment]
Did you get the project's repository with git clone or did you download a ZIP archive from GitHub?

**Comment by felixabi** [comment]
ZIP archive

**Comment by felixabi** [comment]
FİX

**Comment by Ochii** [comment]
What was the issue?

A 23 de setembro de 2019 13:11:23 WEST, Yusuf <notifications@github.com> escreveu:
>Closed #71.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Ochii/cso2-launcher/issues/71#event-2654198128

-- 
Enviado a partir do meu dispositivo Android com o K-9 Mail. Peço desculpa pela brevidade.

**Comment by felixabi** [comment]
I would like to say that it works smoothly with visual studio 2019

**Comment by L-Leite** [comment]
> I would like to say that it works smoothly with visual studio 2019

Those are good knows, thanks for testing
