### ISSUE TITLE
i cant login 

### ISSUE THREAD

**Issue by velcho1541** [Ochii/cso2-launcher#9]
whenever i try to login 

cso2 was forcibly end 

![default](https://user-images.githubusercontent.com/43582653/46030055-0c139100-c130-11e8-9247-2bfd3a9e7cdc.jpg)

**Comment by Tianshee** [comment]
Same.

**Comment by velcho1541** [comment]
Can you explain on pictures or Videos? 

i can`t understand that words 

I don`t know local system and Master Server Instance

**Comment by velcho1541** [comment]
> 로그인하지 말고 오른쪽 상단 구석에있는 홈 이미지를 누르십시오. 
> 음, 그렇지 않을 수도 있습니다. 나는 같은 문제가있다.

i try to that but other probelm was come
i can`t create game  
![default](https://user-images.githubusercontent.com/43582653/46117053-05714080-c23a-11e8-9a02-a24801e1a411.jpg)

**Comment by velcho1541** [comment]
> Make sure you have a master server instance running in your local machine.
> 
> If it's running in some other machine, you can [override the master server's IP address and port number](https://github.com/Ochii/cso2-launcher#available-command-line-arguments)

Can you explain with pictures or Videos?

i can`t understand that words

I don`t know local system and Master Server Instance

**Comment by felixabi** [comment]
Help Me Error Login !

**Comment by Ochii** [comment]
Could you try again with the [new client release](https://github.com/Ochii/cso2-launcher/releases/tag/v0.1.5-1) and the [new master server release](https://github.com/Ochii/cso2-master-server/releases/tag/v0.2.0)?
